/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.tools.metaobjectrenderer;

import Sirius.navigator.ui.ComponentRegistry;
import Sirius.navigator.ui.RequestsFullSizeComponent;

import Sirius.server.middleware.types.MetaObject;

import javax.swing.JComponent;

import de.cismet.tools.gui.FooterComponentProvider;
import de.cismet.tools.gui.TitleComponentProvider;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class ErrorRenderer extends javax.swing.JPanel implements RequestsFullSizeComponent,
    TitleComponentProvider,
    FooterComponentProvider {

    //~ Static fields/initializers ---------------------------------------------

    private static final String NEW_LINE = System.getProperty("line.separator");

    //~ Instance fields --------------------------------------------------------

    private final DefaultMetaObjectRenderer defaultComponent;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefaultRenderer;
    private javax.swing.JButton btnShowProblem;
    private javax.swing.JPanel defaultrendererComponent;
    private javax.swing.JPanel footerComponent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOopsIcon;
    private javax.swing.JLabel lblOopsText;
    private javax.swing.JPanel panOpps;
    private javax.swing.JScrollPane spDefaultRenderer;
    private javax.swing.JPanel stracktraceComponent;
    private javax.swing.JTextPane tpErrorMessage;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ErrorRenderer.
     *
     * @param  throwable  DOCUMENT ME!
     * @param  mo         DOCUMENT ME!
     * @param  title      DOCUMENT ME!
     */
    public ErrorRenderer(final Throwable throwable, final MetaObject mo, final String title) {
        initComponents();
        defaultComponent = (DefaultMetaObjectRenderer)new DefaultMetaObjectRenderer().getSingleRenderer(mo, title);
        spDefaultRenderer.setViewportView(defaultComponent);

        final StringBuilder result = new StringBuilder(throwable.toString()).append(NEW_LINE);

        // add each element of the stack trace
        for (final StackTraceElement element : throwable.getStackTrace()) {
            result.append("\t").append(element).append(NEW_LINE);
        }
        tpErrorMessage.setText(result.toString());
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stracktraceComponent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpErrorMessage = new javax.swing.JTextPane();
        footerComponent = new javax.swing.JPanel();
        btnShowProblem = new javax.swing.JButton();
        btnDefaultRenderer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        defaultrendererComponent = new javax.swing.JPanel();
        spDefaultRenderer = new javax.swing.JScrollPane();
        panOpps = new javax.swing.JPanel();
        lblOopsText = new javax.swing.JLabel();
        lblOopsIcon = new javax.swing.JLabel();

        stracktraceComponent.setOpaque(false);
        stracktraceComponent.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        tpErrorMessage.setEditable(false);
        jScrollPane1.setViewportView(tpErrorMessage);

        stracktraceComponent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footerComponent.setOpaque(false);
        footerComponent.setLayout(new java.awt.GridBagLayout());

        btnShowProblem.setText(org.openide.util.NbBundle.getMessage(
                ErrorRenderer.class,
                "ErrorRenderer.btnShowProblem.text")); // NOI18N
        btnShowProblem.setMaximumSize(new java.awt.Dimension(230, 25));
        btnShowProblem.setMinimumSize(new java.awt.Dimension(230, 25));
        btnShowProblem.setPreferredSize(new java.awt.Dimension(230, 25));
        btnShowProblem.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnShowProblemActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        footerComponent.add(btnShowProblem, gridBagConstraints);

        btnDefaultRenderer.setText(org.openide.util.NbBundle.getMessage(
                ErrorRenderer.class,
                "ErrorRenderer.btnDefaultRenderer.text")); // NOI18N
        btnDefaultRenderer.setMaximumSize(new java.awt.Dimension(230, 25));
        btnDefaultRenderer.setMinimumSize(new java.awt.Dimension(230, 25));
        btnDefaultRenderer.setPreferredSize(new java.awt.Dimension(230, 25));
        btnDefaultRenderer.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnDefaultRendererActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        footerComponent.add(btnDefaultRenderer, gridBagConstraints);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ErrorRenderer.class, "ErrorRenderer.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        footerComponent.add(jLabel1, gridBagConstraints);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ErrorRenderer.class, "ErrorRenderer.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        footerComponent.add(jLabel2, gridBagConstraints);

        defaultrendererComponent.setOpaque(false);
        defaultrendererComponent.setLayout(new java.awt.BorderLayout());

        spDefaultRenderer.setOpaque(false);
        defaultrendererComponent.add(spDefaultRenderer, java.awt.BorderLayout.CENTER);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panOpps.setOpaque(false);
        panOpps.setLayout(new java.awt.GridBagLayout());

        lblOopsText.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblOopsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOopsText.setText(org.openide.util.NbBundle.getMessage(
                ErrorRenderer.class,
                "ErrorRenderer.lblOopsText.text"));              // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panOpps.add(lblOopsText, gridBagConstraints);

        lblOopsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOopsIcon.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/de/cismet/cids/tools/metaobjectrenderer/dialog_error.png"))); // NOI18N
        lblOopsIcon.setText(org.openide.util.NbBundle.getMessage(
                ErrorRenderer.class,
                "ErrorRenderer.lblOopsIcon.text"));                                                    // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panOpps.add(lblOopsIcon, gridBagConstraints);

        add(panOpps, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnDefaultRendererActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnDefaultRendererActionPerformed
        removeAll();
        add(defaultrendererComponent);
        validate();
        repaint();
    }                                                                                      //GEN-LAST:event_btnDefaultRendererActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnShowProblemActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnShowProblemActionPerformed
        removeAll();
        add(stracktraceComponent);
        validate();
        repaint();
    }                                                                                  //GEN-LAST:event_btnShowProblemActionPerformed

    @Override
    public JComponent getTitleComponent() {
        return defaultComponent.getTitleComponent();
    }

    @Override
    public JComponent getFooterComponent() {
        return footerComponent;
    }
}
