/*
 * AdressenEditor.java
 * Copyright (C) 2005 by:
 *
 *----------------------------
 * cismet GmbH
 * Goebenstrasse 40
 * 66117 Saarbruecken
 * http://www.cismet.de
 *----------------------------
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *----------------------------
 * Author:
 * thorsten.hell@cismet.de
 *----------------------------
 *
 * Created on 17. Januar 2006, 14:40
 *
 */

package Sirius.navigator.ui.attributes.editor.metaobject;


/**
 *
 * @author  thorsten.hell@cismet.de
 */
public class AdressenEditor extends DefaultComplexMetaAttributeEditor {
    
    /**
     * Creates new form AdressenEditor 
     */
    public AdressenEditor() {
        super();
        initComponents();
        //super.labelPanel.add(panTitle);
        labelPanel.add(panTitle, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        panTitle.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sirius/navigator/ui/attributes/editor/metaobject/haus.png"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(AdressenEditor.class, "AdressenEditor.jLabel1.text")); // NOI18N
        panTitle.add(jLabel1, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panTitle;
    // End of variables declaration//GEN-END:variables
    
}
