/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package Sirius.navigator.ui.attributes.editor.metaobject;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten.hell@cismet.de
 * @version  $Revision$, $Date$
 */
public class AdressenEditor extends DefaultComplexMetaAttributeEditor {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AdressenEditor.
     */
    public AdressenEditor() {
        super();
        initComponents();
        // super.labelPanel.add(panTitle);
        labelPanel.add(panTitle, java.awt.BorderLayout.CENTER);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        panTitle.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 48));                                                 // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Sirius/navigator/ui/attributes/editor/metaobject/haus.png")));             // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(AdressenEditor.class, "AdressenEditor.jLabel1.text")); // NOI18N
        panTitle.add(jLabel1, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());
    } // </editor-fold>//GEN-END:initComponents
}
