/*
 * MetaClassChooser.java
 *
 * Created on 30. August 2004, 11:29
 */
package Sirius.navigator.ui.tree.editor;

import javax.swing.*;
import java.awt.event.*;

import Sirius.navigator.exception.*;
import Sirius.navigator.resource.*;
import Sirius.navigator.connection.*;
import Sirius.navigator.connection.proxy.*;
import Sirius.navigator.types.treenode.*;
import Sirius.navigator.connection.*;
import Sirius.server.middleware.types.*;
import Sirius.navigator.ui.*;
import java.util.*;
import Sirius.server.newuser.permission.*;

import org.apache.log4j.Logger;

/**
 * Dialog zum Ausw\u00E4hlen einer Klasse.
 *
 * @author  Pascal
 */
public class TreeNodeEditor extends javax.swing.JDialog {

    private ResourceManager resources;
    private DefaultMetaTreeNode metaTreeNode = null;
    private Logger logger;

    /** Creates new form MetaClassChooser */
    public TreeNodeEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        this.logger = Logger.getLogger(this.getClass());
        this.resources = ResourceManager.getManager();
        initComponents();
        getRootPane().setDefaultButton(okButton);
        ActionListener actionListener = new ButtonListener();
        this.okButton.addActionListener(actionListener);
        this.cancelButton.addActionListener(actionListener);
        this.pureNodeRadioButton.addActionListener(actionListener);
        this.classNodeRadioButton.addActionListener(actionListener);
        this.objectNodeRadioButton.addActionListener(actionListener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        javax.swing.JPanel buttonPanel;
        javax.swing.JList classList;
        javax.swing.JPanel editorPanel;
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel infoLabel;
        javax.swing.JScrollPane scrollPane;

        scrollPane = new javax.swing.JScrollPane();
        classList = new javax.swing.JList();
        typeButtonGroup = new javax.swing.ButtonGroup();
        infoLabel = new javax.swing.JLabel();
        editorPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        pureNodeRadioButton = new javax.swing.JRadioButton();
        classNodeRadioButton = new javax.swing.JRadioButton();
        objectNodeRadioButton = new javax.swing.JRadioButton();
        classLabel = new javax.swing.JLabel();
        classBox = new javax.swing.JComboBox();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        classList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane.setViewportView(classList);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(resources.getString("tree.editor.node.title"));
        setLocationRelativeTo(this);
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText(resources.getString("tree.editor.node.message.new"));
        infoLabel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 5, 10)));
        getContentPane().add(infoLabel, java.awt.BorderLayout.NORTH);

        editorPanel.setLayout(new java.awt.GridBagLayout());

        editorPanel.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 10, 5, 10)), new javax.swing.border.EtchedBorder()));
        nameLabel.setText(resources.getString("tree.editor.node.name"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 5, 10);
        editorPanel.add(nameLabel, gridBagConstraints);

        nameField.setMinimumSize(new java.awt.Dimension(200, 20));
        nameField.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 5, 25);
        editorPanel.add(nameField, gridBagConstraints);

        typeLabel.setText(resources.getString("tree.editor.node.type"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 5, 10);
        editorPanel.add(typeLabel, gridBagConstraints);

        pureNodeRadioButton.setText(resources.getString("tree.editor.node.type.pure"));
        typeButtonGroup.add(pureNodeRadioButton);
        pureNodeRadioButton.setActionCommand("pure");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 25);
        editorPanel.add(pureNodeRadioButton, gridBagConstraints);

        classNodeRadioButton.setText(resources.getString("tree.editor.node.type.class"));
        typeButtonGroup.add(classNodeRadioButton);
        classNodeRadioButton.setActionCommand("class");
        classNodeRadioButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 25);
        editorPanel.add(classNodeRadioButton, gridBagConstraints);

        objectNodeRadioButton.setSelected(true);
        objectNodeRadioButton.setText(resources.getString("tree.editor.node.type.object"));
        typeButtonGroup.add(objectNodeRadioButton);
        objectNodeRadioButton.setActionCommand("object");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 25);
        editorPanel.add(objectNodeRadioButton, gridBagConstraints);

        classLabel.setText(resources.getString("tree.editor.node.class"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 25, 10);
        editorPanel.add(classLabel, gridBagConstraints);

        classBox.setMinimumSize(new java.awt.Dimension(200, 19));
        classBox.setPreferredSize(new java.awt.Dimension(200, 19));
        classBox.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 25, 25);
        editorPanel.add(classBox, gridBagConstraints);

        getContentPane().add(editorPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        buttonPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 10, 10, 10)));
        okButton.setMnemonic(resources.getButtonMnemonic("ok"));
        okButton.setText(resources.getButtonText("ok"));
        okButton.setToolTipText(resources.getButtonTooltip("ok"));
        okButton.setActionCommand("ok");
        buttonPanel.add(okButton);

        cancelButton.setMnemonic(resources.getButtonMnemonic("cancel"));
        cancelButton.setText(resources.getButtonText("cancel"));
        cancelButton.setToolTipText(resources.getButtonTooltip("cancel"));
        cancelButton.setActionCommand("cancel");
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox classBox;
    private javax.swing.JLabel classLabel;
    private javax.swing.JRadioButton classNodeRadioButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton objectNodeRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton pureNodeRadioButton;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    public void show() {
        if (this.classBox.getModel().getSize() == 0) {
            try {
                MetaClass[] cs = SessionManager.getProxy().getClasses();
                ArrayList filtered = new ArrayList();

                String key = SessionManager.getSession().getUser().getUserGroup().getKey().toString();
                //Permission perm = SessionManager.getSession().getWritePermission();

                //filtering
                for (int i = 0; i < cs.length; i++) {
                    try {
                        if (cs[i].getPermissions().hasPermission(key, PermissionHolder.WRITEPERMISSION)) {
                            filtered.add(cs[i]);
                        }
                    } catch (Exception e) {
                        logger.debug("filter for " + cs[i]);
                    }
                }

                MetaClass[] csFiltered = (MetaClass[]) filtered.toArray(new MetaClass[filtered.size()]);

                this.classBox.setModel(new DefaultComboBoxModel(csFiltered));
                if (this.classBox.getModel().getSize() > 0) {
                    this.classBox.setSelectedIndex(0);
                }
            } catch (ConnectionException cexp) {
                logger.error("could not load class nodes", cexp);
            }

            this.pack();
        }

        super.show();
    }

    public DefaultMetaTreeNode createTreeNode() {
        this.metaTreeNode = null;
        this.pureNodeRadioButton.setEnabled(true);
        this.objectNodeRadioButton.setSelected(true);
        this.objectNodeRadioButton.setEnabled(true);
        this.classBox.setEnabled(true);

        this.show();
        getRootPane().setDefaultButton(okButton);
        return this.metaTreeNode;
    }

    public DefaultMetaTreeNode editTreeNode(DefaultMetaTreeNode metaTreeNode) {
        this.metaTreeNode = metaTreeNode;

        this.nameField.setText(metaTreeNode.toString());
        this.pureNodeRadioButton.setEnabled(false);
        this.classNodeRadioButton.setEnabled(false);
        this.objectNodeRadioButton.setEnabled(false);
        this.classBox.setEnabled(false);

        this.show();
        getRootPane().setDefaultButton(okButton);
        return this.metaTreeNode;
    }

    public DefaultMetaTreeNode getMetaTreeNode() {
        return this.metaTreeNode;
    }

    protected class ButtonListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            if (e.getActionCommand().equals("ok")) {
                if (TreeNodeEditor.this.nameField.getText().length() > 0) {
                    // create
                    if (metaTreeNode == null) {
                        // new pure node
                        if (TreeNodeEditor.this.pureNodeRadioButton.isSelected()) {
                            MetaNode metaNode = new MetaNode(-1, SessionManager.getSession().getUser().getDomain(), TreeNodeEditor.this.nameField.getText(), null, true, Policy.createWIKIPolicy(), -1, null, false, -1);
                            TreeNodeEditor.this.metaTreeNode = new PureTreeNode(metaNode);

                            TreeNodeEditor.this.dispose();
                        } else if (TreeNodeEditor.this.classNodeRadioButton.isSelected()) {
                            //XXX
                        } else if (TreeNodeEditor.this.objectNodeRadioButton.isSelected()) {
                            if (TreeNodeEditor.this.classBox.getSelectedIndex() >= 0) {
                                try {
                                    MetaClass metaClass = (MetaClass) TreeNodeEditor.this.classBox.getSelectedItem();

                                    if (logger.isDebugEnabled()) {
                                        logger.debug("actionPerformed(): creating new meta object node of type " + metaClass);
                                    }

                                    ComponentRegistry.getRegistry().getMainWindow().setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
                                    MetaObject MetaObject = SessionManager.getProxy().getInstance(metaClass);
                                    ComponentRegistry.getRegistry().getMainWindow().setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));

                                    MetaObjectNode MetaObjectNode = new MetaObjectNode(-1, SessionManager.getSession().getUser().getDomain(), MetaObject, TreeNodeEditor.this.nameField.getText(), null, true, Policy.createWIKIPolicy(), -1, null, false);
                                    TreeNodeEditor.this.metaTreeNode = new ObjectTreeNode(MetaObjectNode);

                                    TreeNodeEditor.this.dispose();
                                } catch (Throwable t) {
                                    logger.error("actionPerformed(): could not create new empty meta object", t);
                                    ComponentRegistry.getRegistry().getMainWindow().setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));

                                    JOptionPane.showMessageDialog(ComponentRegistry.getRegistry().getMainWindow(), resources.getString("tree.editor.node.error.server.1") + TreeNodeEditor.this.classBox.getSelectedItem() + resources.getString("tree.editor.node.error.server.2") + t.getMessage() + resources.getString("tree.editor.node.error.server.3"), resources.getString("tree.editor.node.error.server.title"), JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                logger.warn("actionPerformed() no class");
                                JOptionPane.showMessageDialog(ComponentRegistry.getRegistry().getMainWindow(), resources.getString("tree.editor.node.error.noclass"), resources.getString("tree.editor.node.error.noclass.title"), JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    } else {
                        metaTreeNode.getNode().setName(nameField.getText());
                        metaTreeNode.setChanged(true);

                        TreeNodeEditor.this.dispose();
                    }
                } else {
                    logger.warn("actionPerformed() no name");
                    JOptionPane.showMessageDialog(ComponentRegistry.getRegistry().getMainWindow(), resources.getString("tree.editor.node.error.noname"), resources.getString("tree.editor.node.error.noname.title"), JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (e.getActionCommand().equals("cancel")) {
                TreeNodeEditor.this.metaTreeNode = null;
                TreeNodeEditor.this.dispose();
            } else if (e.getActionCommand().equals("pure")) {
                TreeNodeEditor.this.classBox.setEnabled(false);
            } else if (e.getActionCommand().equals("class")) {
                TreeNodeEditor.this.classBox.setEnabled(true);
            } else if (e.getActionCommand().equals("object")) {
                TreeNodeEditor.this.classBox.setEnabled(true);
            }
        }
    }
}
