/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sirius.navigator.ui.attributes.renderer;

import Sirius.navigator.types.treenode.DefaultMetaTreeNode;

import javax.swing.JComponent;

import de.cismet.tools.gui.TitleComponentProvider;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class NoDescriptionRenderer extends javax.swing.JPanel implements TitleComponentProvider {

    //~ Static fields/initializers ---------------------------------------------

    private static NoDescriptionRenderer INSTANCE = new NoDescriptionRenderer();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NoDescriptionRenderer.
     */
    public NoDescriptionRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static NoDescriptionRenderer getInstance() {
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(org.openide.util.NbBundle.getMessage(
                NoDescriptionRenderer.class,
                "NoDescriptionRenderer.lblTitle.text")); // NOI18N

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Sirius/navigator/ui/attributes/renderer/nodescription_icon.png"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(
                NoDescriptionRenderer.class,
                "NoDescriptionRenderer.jLabel2.text"));                                                      // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 25, 10);
        add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Sirius/navigator/ui/attributes/renderer/nodescription_text.png"))); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(
                NoDescriptionRenderer.class,
                "NoDescriptionRenderer.jLabel3.text"));                                                      // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 10, 10);
        add(jLabel3, gridBagConstraints);
    }                                                                                                        // </editor-fold>//GEN-END:initComponents

    @Override
    public JComponent getTitleComponent() {
        return lblTitle;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  title  node DOCUMENT ME!
     */
    public void setTitle(final String title) {
        lblTitle.setText(title);
    }
}
