package Sirius.navigator.ui.dialog;

import java.io.*;

import Sirius.navigator.resource.*;

/**
 *
 * @author  pascal
 */
public class AboutDialog extends javax.swing.JDialog
{
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent)
    {
        super(parent, true);
        initComponents();
        
        try
        {
            StringBuffer buffer = new StringBuffer();
            String string = null;
            BufferedReader reader = new BufferedReader(new InputStreamReader(ResourceManager.getManager().getNavigatorResourceAsStream(ResourceManager.getManager().getString("about.html"))));
        
            while((string = reader.readLine()) != null)
            {
                buffer.append(string);
            }
            
            this.aboutLabel.setText(buffer.toString());
        }
        catch(IOException ioexp)
        {
            //logger.warn("could not load html about file", ioexp);
            this.aboutLabel.setText(ResourceManager.getManager().getString("about.default"));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        aboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("AboutDialog");
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        aboutPanel.setLayout(new java.awt.GridLayout(1, 1));

        aboutPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        aboutLabel.setBackground(new java.awt.Color(255, 255, 240));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setToolTipText(ResourceManager.getManager().getString("about.tooltip"));
        aboutLabel.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10))));
        aboutLabel.setPreferredSize(null);
        aboutLabel.setOpaque(true);
        aboutPanel.add(aboutLabel);

        getContentPane().add(aboutPanel, java.awt.BorderLayout.CENTER);

        closePanel.setLayout(new java.awt.GridLayout(1, 0));

        closePanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 5, 5, 5)));
        closeButton.setMnemonic(ResourceManager.getManager().getButtonMnemonic("close"));
        closeButton.setText(ResourceManager.getManager().getButtonText("close"));
        closeButton.setToolTipText(ResourceManager.getManager().getButtonTooltip("close"));
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        closePanel.add(closeButton);

        getContentPane().add(closePanel, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // Add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[])
    {
        AboutDialog aboutDialog = new AboutDialog(new javax.swing.JFrame());
        aboutDialog.setLocationRelativeTo(null);
        aboutDialog.pack();
        aboutDialog.show();
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel closePanel;
    // End of variables declaration//GEN-END:variables
    
}
