/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package Sirius.navigator.search;

import Sirius.navigator.ui.ComponentRegistry;

import Sirius.server.middleware.types.MetaObjectNode;

import java.util.ArrayList;
import java.util.List;

import de.cismet.commons.gui.protocol.AbstractProtocolStepPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class CidsServerSearchProtocolStepPanel extends AbstractProtocolStepPanel<CidsServerSearchProtocolStep> {

//    private static final Map<String, ImageIcon> ICON_MAP = new HashMap<String, ImageIcon>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private Sirius.navigator.search.CidsServerSearchProtocolStepResultsTree protocolResultsTree1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * konstruktor ohne parameter wird für gui designer gebraucht, wenn dieses panel in ein anderes benutzt werden soll.
     */
    public CidsServerSearchProtocolStepPanel() {
        this(new CidsServerSearchProtocolStepImpl(null, new ArrayList<MetaObjectNode>()));
    }

    /**
     * Creates new form CidsSearchProtocolStepPanel.
     *
     * @param  cidsSearchProtocolStep  DOCUMENT ME!
     */
    public CidsServerSearchProtocolStepPanel(final CidsServerSearchProtocolStep cidsSearchProtocolStep) {
        super(cidsSearchProtocolStep);
        initComponents();

        jButton1.setVisible(cidsSearchProtocolStep.isReExecuteSearchEnabled());
        protocolResultsTree1.setResultNodes(cidsSearchProtocolStep.getSearchResultNodes().toArray(
                new MetaObjectNode[0]));

        setSearchResultsPanelVisible(false);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private List<MetaObjectNode> getSearchResultNodesList() {
        if (getProtocolStep() != null) {
            final List<MetaObjectNode> searchObjectNodes = ((CidsServerSearchProtocolStep)getProtocolStep())
                        .getSearchResultNodes();
            if (searchObjectNodes != null) {
                return searchObjectNodes;
            }
        }
        return new ArrayList<MetaObjectNode>();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        try {
            protocolResultsTree1 = new Sirius.navigator.search.CidsServerSearchProtocolStepResultsTree();
        } catch (java.lang.Exception e1) {
            e1.printStackTrace();
        }
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(
            jButton1,
            org.openide.util.NbBundle.getMessage(
                CidsServerSearchProtocolStepPanel.class,
                "CidsServerSearchProtocolStepPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jButton1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jXHyperlink1,
            org.openide.util.NbBundle.getMessage(
                CidsServerSearchProtocolStepPanel.class,
                "CidsServerSearchProtocolStepPanel.jXHyperlink1.text")); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jXHyperlink1ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jXHyperlink1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setViewportView(protocolResultsTree1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jButton2,
            org.openide.util.NbBundle.getMessage(
                CidsServerSearchProtocolStepPanel.class,
                "CidsServerSearchProtocolStepPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jPanel2, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
        ((CidsServerSearchProtocolStep)getProtocolStep()).reExecuteSearch();
    }                                                                            //GEN-LAST:event_jButton1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jXHyperlink1ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jXHyperlink1ActionPerformed
        toggleSearchResultsPanelVisibility();
    }                                                                                //GEN-LAST:event_jXHyperlink1ActionPerformed

    /**
     * DOCUMENT ME!
     */
    private void toggleSearchResultsPanelVisibility() {
        setSearchResultsPanelVisible(!jPanel2.isVisible());
    }

    /**
     * DOCUMENT ME!
     *
     * @param  visible  DOCUMENT ME!
     */
    private void setSearchResultsPanelVisible(final boolean visible) {
        jPanel2.setVisible(visible);

        if ((getSearchResultNodesList() == null) || getSearchResultNodesList().isEmpty()) {
            jXHyperlink1.setVisible(false);
        } else {
            jXHyperlink1.setVisible(true);
            if (jPanel2.isVisible()) {
                jXHyperlink1.setText(Integer.toString(getSearchResultNodesList().size()) + " Suchergebnisse verbergen");
            } else {
                jXHyperlink1.setText(Integer.toString(getSearchResultNodesList().size()) + " Suchergebnisse anzeigen");
            }
        }

        revalidate();
    }

    /**
     * DOCUMENT ME!
     */
    private void loadSearchResultsIntoTree() {
        final List<MetaObjectNode> mons = getSearchResultNodesList();
        ComponentRegistry.getRegistry().getSearchResultsTree().setResultNodes(mons.toArray(new MetaObjectNode[0]));
    }

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jButton2ActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
        loadSearchResultsIntoTree();
    }                                                                            //GEN-LAST:event_jButton2ActionPerformed
}
