package de.cismet.reconnector;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JLabel;

/**
 *
 * @author  jruiz
 */
public class ReconnectorPanel extends javax.swing.JPanel implements ReconnectorListener {

    private final static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(ReconnectorPanel.class);
    
    private final static String CONNECTION_CANCELED = java.util.ResourceBundle.getBundle("de/cismet/reconnector/Bundle").getString("connection_canceled");

    private final Reconnector reconnector;

    /** Creates new form ReconnectorPanel */
    public ReconnectorPanel(final Reconnector reconnector) {
        this.reconnector = reconnector;
        
        initComponents();

        setConnecting(false);
    }

    private void setConnecting(final boolean isConnecting) {
        removeAll();
        if (isConnecting) {
            add(panProgress, BorderLayout.CENTER);
        } else {
            add(panRetry, BorderLayout.CENTER);
        }
        revalidate();
        validate();
        repaint();
    }

    private void showError(final Component component) {
        panError.add(component, BorderLayout.CENTER);
        if (component instanceof Container) {
            Container cont = (Container)component;
            cont.addComponentListener(new ComponentAdapter() {

                @Override
                public void componentResized(ComponentEvent ce) {
                    reconnector.pack();
                }

            });
        }
        setConnecting(false);
    }

    private void showConnecting() {
        panError.removeAll();
        setConnecting(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panProgress = new javax.swing.JPanel();
        pb = new javax.swing.JProgressBar();
        btnCancel = new javax.swing.JButton();
        labTryingToConnect = new javax.swing.JLabel();
        panRetry = new javax.swing.JPanel();
        panError = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAbort = new javax.swing.JButton();
        btnRetry = new javax.swing.JButton();

        panProgress.setMinimumSize(new java.awt.Dimension(200, 88));
        panProgress.setLayout(new java.awt.GridBagLayout());

        pb.setBorderPainted(false);
        pb.setIndeterminate(true);
        pb.setPreferredSize(new java.awt.Dimension(200, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        panProgress.add(pb, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/cismet/reconnector/Bundle"); // NOI18N
        btnCancel.setText(bundle.getString("cancel")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        panProgress.add(btnCancel, gridBagConstraints);

        labTryingToConnect.setText(bundle.getString("trying_to_connect")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        panProgress.add(labTryingToConnect, gridBagConstraints);

        panRetry.setMinimumSize(new java.awt.Dimension(200, 53));
        panRetry.setLayout(new java.awt.GridBagLayout());

        panError.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        panRetry.add(panError, gridBagConstraints);

        btnAbort.setText("Abbrechen");
        btnAbort.setPreferredSize(new java.awt.Dimension(125, 29));
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbort);

        btnRetry.setText(bundle.getString("retry")); // NOI18N
        btnRetry.setPreferredSize(new java.awt.Dimension(125, 29));
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetry);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panRetry.add(jPanel1, gridBagConstraints);

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        reconnector.doCancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed
        reconnector.doReconnect();
    }//GEN-LAST:event_btnRetryActionPerformed

    private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
        reconnector.doAbbort();
    }//GEN-LAST:event_btnAbortActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRetry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labTryingToConnect;
    private javax.swing.JPanel panError;
    private javax.swing.JPanel panProgress;
    private javax.swing.JPanel panRetry;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void connecting() {
        showConnecting();
    }

    @Override
    public void connectionFailed(ReconnectorEvent event) {
        showError(event.getComponent());
    }

    @Override
    public void connectionCanceled() {
        showError(new JLabel(CONNECTION_CANCELED));
    }

    @Override
    public void connectionCompleted() {
    }
    
}
